### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jkimsis** [grenaud/deML#14]
Hello,

I'm getting a compilation error

/home/jkimsis/install/deML/bamtools/src/api/internal/bam/BamMultiMerger_p.h:135:18:   required from ?void BamTools::Internal::MultiMerger<Compare>::Add(BamTools::Internal::MergeItem) [with Compare = BamTools::Algorithms::Sort::ByPosition]?
/home/jkimsis/install/deML/bamtools/src/api/internal/bam/BamMultiMerger_p.h:128:13:   required from here
**/usr/include/c++/12/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const**
/usr/include/c++/12/bits/stl_tree.h:770:15: note: ?std::is_invocable_v<const BamTools::Internal::MergeItemSorter<BamTools::Algorithms::Sort::ByPosition>&, const BamTools::Internal::MergeItem&, const BamTools::Internal::MergeItem&>? evaluates to false
make[3]: *** [src/api/CMakeFiles/BamTools.dir/build.make:244: src/api/CMakeFiles/BamTools.dir/internal/bam/BamMultiReader_p.cpp.o] Error 1
make[3]: Leaving directory '/home/jkimsis/install/deML/bamtools/build'
make[2]: *** [CMakeFiles/Makefile2:318: src/api/CMakeFiles/BamTools.dir/all] Error 2
make[2]: Leaving directory '/home/jkimsis/install/deML/bamtools/build'
make[1]: *** [Makefile:136: all] Error 2
make[1]: Leaving directory '/home/jkimsis/install/deML/bamtools/build'
make: *** [Makefile:32: bamtools/build/src/api/libbamtools.a] Error 2

I've already found a similar issue in an [unrelated git](https://github.com/NVIDIA/TensorRT/issues/1783), which was solved by using g++ 8 instead of of a newer one. Is there a way to fix this or should I just try to get the older g++ version?

**Comment by jkimsis** [comment]
I'm getting the same problem trying to install [schmutzi](https://github.com/grenaud/schmutzi)

**Comment by grenaud** [comment]
I think this is a bamtools problem no?

I just added a static binary for deML, can you check if it works?

**Comment by jkimsis** [comment]
Yup, everything's working fine.
