### ISSUE TITLE
Citing deML

### ISSUE THREAD

**Issue by jkimsis** [grenaud/deML#17]
Hello,

do you have a preferred way to cite deML?

**Comment by grenaud** [comment]
Yes, please cite our paper in Bioinformatics :-)


Renaud, Gabriel, Udo Stenzel, Tomislav Maricic, Victor Wiebe, and Janet Kelso. "deML: robust demultiplexing of Illumina sequences using a likelihood-based approach." Bioinformatics 31, no. 5 (2015): 770-772.

or in bibtex:
`@article{renaud2015deml,
  title={{deML: robust demultiplexing of Illumina sequences using a likelihood-based approach}},
  author={Renaud, Gabriel and Stenzel, Udo and Maricic, Tomislav and Wiebe, Victor and Kelso, Janet},
  journal={{Bioinformatics}},
  volume={31},
  number={5},
  pages={770--772},
  year={2015},
  publisher={Oxford University Press}
}`
