### ISSUE TITLE
unexpected end of file

### ISSUE THREAD

**Issue by DeaconOfBiology** [grenaud/deML#20]
Hey,
The program runs great. However, when I test the quality of the output files with gzip -t I get the following error "unexpected end of file". When I look up the meaning of the error the googles tells me that it means my file is corrupt. However, when i check the input file, everything is fine. So, Im not sure how to proceed. Thanks for any advise you can give

**Comment by TJrogers86** [comment]
Scratch that. The problem came about because I was running deML in a for loop with '&' so it would run in parallel. Fixed the issue

**Comment by DeaconOfBiology** [comment]
Scratch that. The problem came about because I was running deML in a for loop with '&' so it would run in parallel. Fixed the issue
