### ISSUE TITLE
Installation error when building the source code

### ISSUE THREAD

**Issue by chang-wang** [grenaud/deML#3]
Hi,

My colleagues got some error messages when he helped me to install deML on the cluster. He told me there were no functions returnOpenFileDescriptors and returnOpenFileDescriptorsMax declared when he tried to build the source code. Here are the error messages he attached to me:

deML.cpp: In function ‘void checkFD()’:
deML.cpp:587:43: error: ‘returnOpenFileDescriptors’ was not declared in this scope
     int rofd  = returnOpenFileDescriptors();
                                           ^
deML.cpp:588:46: error: ‘returnOpenFileDescriptorsMax’ was not declared in this scope
     int rofdM = returnOpenFileDescriptorsMax();

We couldn't find information regarding this issue online. Could you please help me to take a look at it? Thanks a lot!

**Comment by grenaud** [comment]
Dear Chang,
Thank you for your interest in our work! 
I checked your problem, it seems that when you do "git clone --recursive" followed by make, it does not fetch the latest version of libgab. However, when you do "git clone" followed by make, then the correct version of libgab is used. I have no idea why. If you can find an explanation, please let me know.

In the meantime, I changed the readme from:
`2. Do a "git clone  --recursive https://github.com/grenaud/deML.git"`
 to
`2. Do a "git clone  https://github.com/grenaud/deML.git"`

please let me know if this solves the problem on your end.

**Comment by chang-wang** [comment]
Thanks a lot! Problem solved~
