### ISSUE TITLE
concerns on this software

### ISSUE THREAD

**Issue by chloelulu** [grenaud/deML#8]
Hi, 
Thanks so much for creating this software. Just now I tried to demultiplex my data very quickly. But the output makes me confusing. Since many outputs I did not expected, shown in figure below. I only have one index.fq 
![image](https://user-images.githubusercontent.com/28763565/51418374-2e9f3f00-1b51-11e9-8d9c-9414b50457d9.png)
Some fail.fq, some unknow.fq. which make me confusing. 
The code I am using is `src/deML -i index.txt -f sample_S0_L001_R1_001.fastq  -r sample_S0_L001_R2_001.fastq -if1 sample_S0_L001_I1_001.fastq -o demultiplexed.`
The format of my fq input files are shown in the picture below. May I know are there anything wrong? Thanks so much. 
![image](https://user-images.githubusercontent.com/28763565/51418439-8473e700-1b51-11e9-9706-d88743b809ba.png)
And my index file

![image](https://user-images.githubusercontent.com/28763565/51418532-f2b8a980-1b51-11e9-8ac5-e6bdc3bfbb42.png)

**Comment by grenaud** [comment]
The description for each of the categories is found in the README here:
https://github.com/grenaud/deML

Could you check the index for the ones for the different categories, there must be a reason why they get classified as such. Fail must be due to mismatches between the index templates and the sequenced indices.

**Comment by grenaud** [comment]
have you had any luck with the README? I am just wondering if I can close this issue.

**Comment by chloelulu** [comment]
Hi, @grenaud ,

Thanks so much! The problem has been solved!
