### ISSUE TITLE
Using deML with dual indexed reads

### ISSUE THREAD

**Issue by ahwanpandey** [grenaud/deML#9]
Hello,

I have a similar query as in this biostar question that hasn't been answered yet.

https://www.biostars.org/p/342946/

I don't get an error per say but just making sure that the tool is compatible with dual indexed adapters where the combination of the indexes in unique but they might not be unique by themselves.

Would really appreciate any feedback!

Thanks.

**Comment by grenaud** [comment]
@ahwanpandey  thank you for bringing this post to my attention. I have replied on biostars, let me know if my answer is satisfactory.

**Comment by ahwanpandey** [comment]
Thanks @grenaud . Makes sense!
